### PR TITLE
Yubikey: Adding option to suppress "enter" at the end of the generate…

### PR DESCRIPTION
**Pull request by fhibler**
…d OTP

This one goes as solution for issue #27

### CODE REVIEW

**Comment by fhibler** [comment]
Due to the nature of YubiKey nanos it can be very annoying for users to have the "enter" function on after the OTP has been generated. I'll provide a pull request to fix this issue soon.
I closed #27 because it was a duplicate.

**Comment by challs** [comment]
Hi @fhibler 

Many thanks for your patch. In order to integrate into LinOTP, a contribution agreement is needed. Could you please drop an email to linotp-community (at) lsexperts.de from the address which we can contact you? Thank you!

**Comment by fhibler** [comment]
Hi @challs,
I emailed in some while ago, but unfortunately no one responded yet.

**Comment by gregharvey** [comment]
FWIW, you can automate contributor agreement signing with GitHub by setting automated requirements for PRs - see how Rocket.Chat do it, it's pretty sweet! :-)

https://github.com/RocketChat/Rocket.Chat.Docs/pull/232

**Pull request closed without merging**
